// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFbTK9p0tNRSSUS83zMMT0Kr9locgDvx4',
    appId: '1:649439731784:web:735d22d99dcf78032ef87d',
    messagingSenderId: '649439731784',
    projectId: 'traveler-e8541',
    authDomain: 'traveler-e8541.firebaseapp.com',
    storageBucket: 'traveler-e8541.appspot.com',
    measurementId: 'G-2JFKV4L047',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcDNlbVQZwW2KMX5WXAXucmce3tbkoN1c',
    appId: '1:649439731784:android:5d673fd37012eba42ef87d',
    messagingSenderId: '649439731784',
    projectId: 'traveler-e8541',
    storageBucket: 'traveler-e8541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUPDhdiD8IJM-x4LKeotN6es5AU8_idkw',
    appId: '1:649439731784:ios:8a820b9d8f5e88a92ef87d',
    messagingSenderId: '649439731784',
    projectId: 'traveler-e8541',
    storageBucket: 'traveler-e8541.appspot.com',
    iosClientId: '649439731784-t0282l3ra216nmmo04acatqc82qd8d5l.apps.googleusercontent.com',
    iosBundleId: 'com.traveler.traveler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUPDhdiD8IJM-x4LKeotN6es5AU8_idkw',
    appId: '1:649439731784:ios:8a820b9d8f5e88a92ef87d',
    messagingSenderId: '649439731784',
    projectId: 'traveler-e8541',
    storageBucket: 'traveler-e8541.appspot.com',
    iosClientId: '649439731784-t0282l3ra216nmmo04acatqc82qd8d5l.apps.googleusercontent.com',
    iosBundleId: 'com.traveler.traveler',
  );
}
